version: '3'
services:
  frontend:
    build: 
      context: .
      dockerfile: ./containers/frontend/Dockerfile
    container_name: frontend
    volumes:
      - ./react/:/usr/src/app
    ports:
      - "80:80"
