name: "login to ecr"
inputs:
  ecr_registory:
    required: true
  iam_role:
    required: true
  
outputs:
  ecr-retistry:
    value: ${{ steps.login-ecr.outputs.registry }}
runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.region }}
        role-to-assume: ${{ inputs.iam_role }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
