name: "push contaienr to ecr"

inputs:
  region:
    required: true
  iam_role:
    required: true
  repository:
    required: true
  dockerfile_dir:
    required: true
  args:
    required: false

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{inputs.region}}
        role-to-assume: ${{inputs.iam_role}}
    - name: Login to Amazon ECR
      id: login
      uses: aws-actions/amazon-ecr-login@v1
    - name: push container
      id: build-and-push
      uses: docker/build-push-action@v2
      with:
        push: true
        file: ${{inputs.dockerfile_dir}}
        tags: ${{steps.login.outputs.registry}}/${{inputs.repository}}:latest
        context: ./app
        build-args: ${{inputs.args}}
        
