name: "push contaienr to ecr"

inputs:
  region:
    required: true
  iam_role:
    required: true
  tag:
    required: true
  repository:
    required: true
  dockerfile_dir:
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.region }}
        role-to-assume: ${{ inputs.iam_role }}
    - name: Login to Amazon ECR
      id: login
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: push container
      uses: docker/build-push-action@v2
      id: build-image
      with:
        push: true
        file: ${{ inputs.dockerfile_dir }}
        tags: ${{ steps.login.outputs.ecr-registry }}/${{ inputs.repository }}:latest

      #shell: sh
      #env:
      #  IMAGE_TAG: latest
      #  REGISTORY: ${{ steps.login.outputs.ecr-registry }}
      #  REPOSITORY: ${{ inputs.repository }}
      #  PATH: 
      #run: |
      #  cd app/
      #  docker build -t $REGISTORY/$REPOSITORY:$IMAGE_TAG -f $PATH .
      #  docker push $REGISTORY/$REPOSITORY:$IMAGE_TAG