name: "push contaienr to ecr"
inputs:
  tag:
    required: true
  registory:
    required: true
  repository:
    required: true
  dockerfile_dir:
    required: true

runs:
  using: "composite"
  steps:
    - name: push container
      run: |
        cd app/
        IMAGE_TAG=$(echo ${{ inputs.tag }} | sed -e "s#refs/tags/##g")
        docker build -t ${{ inputs.registory }}/${{ inputs.repository }}:$IMAGE_TAG -f ${{ inputs.dockerfile_dir }} .
        docker push ${{ inputs.registory }}/${{ inputs.repository }}:$IMAGE_TAG