name: deploy

on:
  push:
    branches:
    - main

jobs:
  s3ls:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.REGION }}
          role-to-assume: ${{ secrets.IAM_ROLE }}
      - run: aws s3 ls