name: deploy

on:
  push:
    paths:
      - '.github/**'  
      - 'app/**'  
      - 'infra/**'  
    branches:
      - main
    tags:
      - v*
jobs:
  infra:
    runs-on: ubuntu-latest
    steps:
    - run: echo "do infra job" ## terraform deployに修正
  app:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.REGION }}
          role-to-assume: ${{ secrets.IAM_ROLE }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            front:
              - 'app/containers/frontend/**'
              - 'app/react_frontend/**'
              - 'app/nginx/**'
            back:
              - 'app/containers/frontend/**'
              - 'app/react_frontend/**'
              - 'app/nginx/**'
            db:
              - 'app/containers/db/**'
      - name: push to ECR
        run: cd app/
      - if: steps.filter.outputs.front == 'true'
        name: front
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_FRONT_REPO }}
          DOCKERFILE_DIR: containers/frontend/Dockerfile
        run: |
          IMAGE_TAG=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f $DOCKERFILE_DIR .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG