name: deploy

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  pushImageToECR:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.REGION }}
          role-to-assume: ${{ secrets.IAM_ROLE }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: push front container
        id: changes
        with:
          filters: |
            front:
              - 'app/containers/frontend/**'
              - 'app/react_frontend/**'
              - 'app/nginx/**'
            back:
              - 'app/containers/frontend/**'
              - 'app/react_frontend/**'
              - 'app/nginx/**'
            db:
              - 'app/containers/db/**'

        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_FRONT_REPO }}
          DOCKERFILE_DIR: containers/frontend/Dockerfile
        - if: steps.front_changes.outputs.src == 'true'
        run: |
          cd app/
          IMAGE_TAG=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f $DOCKERFILE_DIR .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG