name: deploy

on:
  push:
    paths:
      - 'app/**'  
    branches:
      - main
env:
  APP: blog
  ENV: staging
  FRONT_CONTAINER_BUILD_TARGET: prd

permissions:
  id-token: write
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      app_front: ${{steps.filter.outputs.app_front}}
      app_back: ${{steps.filter.outputs.app_back}}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            app_front:
              - 'app/containers/frontend/**'
              - 'app/react_frontend/**'
              - 'app/nginx/**'
            app_back:
              - 'app/containers/backend/**'
              - 'app/rails/**'
  app_front:
    needs: changes
    if: ${{needs.changes.outputs.app_front == 'true'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: push_container
        uses: ./.github/actions/push_container
        with:
          region: ${{secrets.REGION}}
          iam_role: arn:aws:iam::${{secrets.ACCOUNT_ID}}:role/${{env.APP}}-github-actions-role-${{env.ENV}}
          repository: ${{env.APP}}-front-${{env.ENV}}
          dockerfile_dir: ./app/containers/frontend/Dockerfile
          args: |
            "
            FRONT_CONTAINER_BUILD_TARGET: ${{env.FRONT_CONTAINER_BUILD_TARGET}}
            "
  app_back:
    needs: changes
    if: ${{needs.changes.outputs.app_back == 'true'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: push_container
        uses: ./.github/actions/push_container
        with:
          region: ${{secrets.REGION}}
          iam_role: arn:aws:iam::${{secrets.ACCOUNT_ID}}:role/${{env.APP}}-github-actions-role-${{env.ENV}}
          repository: ${{env.APP}}-back-${{env.ENV}}
          dockerfile_dir: ./app/containers/backend/Dockerfile
          args: |
            "
            DB_USERNAME: ${{secrets.DB_USERNAME}}
            DB_PASSWORD: ${{secrets.DB_PASSWORD}}
            DB_HOST: ${{secrets.DB_PASSWORD}}
            DB_NAME: ${{env.APP}}
            "
