name: deploy

on:
  push:
    paths:
      - '.github/**'  
      - 'app/**'  
      - 'infra/**'  
    branches:
      - main
    tags:
      - v*
jobs:
  infra:
    runs-on: ubuntu-latest
    steps:
    - run: echo "do infra job" ## terraform deployに修正
  app:
    runs-on: ubuntu-latest
    needs: infra
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: login
        uses: ./.github/actions/ecr_login
        with:
          region: ${{ secrets.REGION }}
          iam_role: ${{ secrets.IAM_ROLE }}
      - id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            front:
              - 'app/containers/frontend/**'
              - 'app/react_frontend/**'
              - 'app/nginx/**'
            back:
              - 'app/containers/frontend/**'
              - 'app/react_frontend/**'
              - 'app/nginx/**'
      - name: push_container
        uses: ./.github/actions/push_container
        with:
          tag: ${{ github.ref }}
          ecr_registory: ${{ steps.login.outputs.ecr-retistry }}
          ecr_repository: ${{ secrets.ECR_FRONT_REPO }}
          dockerfile_dir: containers/frontend/Dockerfile
      - if: steps.filter.outputs.front == 'true'
        name: front
        run: |
          cd app/
          IMAGE_TAG=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f $DOCKERFILE_DIR .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG