name: deploy

on:
  push:
    paths:
      - '.github/**'  
      - 'app/**'  
      - 'infra/**'  
    branches:
      - main
    tags:
      - v*
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      app_front: ${{ steps.filter.outputs.app_front }}
      app_back: ${{ steps.filter.outputs.app_back }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          infra:
            - 'infra/**'
          app_front:
            - 'app/containers/frontend/**'
            - 'app/react_frontend/**'
            - 'app/nginx/**'
          app_back:
            - 'app/containers/frontend/**'
            - 'app/react_frontend/**'
            - 'app/nginx/**'

  infra:
    runs-on: ubuntu-latest
    needs: changes
    steps:
    - run: echo "do infra job" ## terraform deployに修正
  
  app_front:
    needs: infra
    if: ${{ needs.changes.outputs.app_front == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: push_container
        uses: ./.github/actions/push_container
        with:
          region: ${{ secrets.REGION }}
          iam_role: ${{ secrets.IAM_ROLE }}
          tag: ${{ github.ref }}
          ecr_repository: ${{ secrets.ECR_FRONT_REPO }}
          dockerfile_dir: containers/frontend/Dockerfile
