name: deploy

on:
  push:
    paths:
      - 'app/**'  
      - 'infra/**'  
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      app_front: ${{ steps.filter.outputs.app_front }}
      app_back: ${{ steps.filter.outputs.app_back }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          infra:
            - 'infra/**'
          app_front:
            - 'app/containers/frontend/**'
            - 'app/react_frontend/**'
            - 'app/nginx/**'
          app_back:
            - 'app/containers/backend/**'
            - 'app/rails/**'

  infra:
    needs: changes
    if: ${{ needs.changes.outputs.infra == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - run: echo "do infra job" ## terraform deployに修正
  
  app_front:
    needs: changes
    if: ${{ needs.changes.outputs.app_front == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: push_container
        uses: ./.github/actions/push_container
        with:
          region: ${{ secrets.REGION }}
          iam_role: ${{ secrets.IAM_ROLE }}
          tag: ${{ github.ref }}
          repository: ${{ secrets.ECR_FRONT_REPO }}
          dockerfile_dir: ./app/containers/frontend/Dockerfile
  app_back:
    needs: changes
    if: ${{ needs.changes.outputs.app_back == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: push_container
        uses: ./.github/actions/push_container
        with:
          region: ${{ secrets.REGION }}
          iam_role: ${{ secrets.IAM_ROLE }}
          repository: ${{ secrets.ECR_BACK_REPO }}
          dockerfile_dir: ./app/containers/backend/Dockerfile
