name: deploy

on:
  push:
    paths:
      - 'app/**'  
      - 'infra/**'  
    branches:
      - main
env:
  terraform_ver: 1.3.6
  ecr_front_repo: workout-front-staging
  ecr_back_repo: workout-back-staging


jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      app_front: ${{ steps.filter.outputs.app_front }}
      app_back: ${{ steps.filter.outputs.app_back }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          infra:
            - 'infra/**'
          app_front:
            - 'app/containers/frontend/**'
            - 'app/react_frontend/**'
            - 'app/nginx/**'
          app_back:
            - 'app/containers/backend/**'
            - 'app/rails/**'

  infra:
    needs: changes
    if: ${{ needs.changes.outputs.infra == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ secrets.REGION }}
        role-to-assume: ${{ secrets.IAM_ROLE }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.terraform_ver }}
    - run: terraform fmt -recursive -check

  
  app_front:
    needs: changes
    if: ${{ needs.changes.outputs.app_front == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: push_container
        uses: ./.github/actions/push_container
        with:
          region: ${{ secrets.REGION }}
          iam_role: ${{ secrets.IAM_ROLE }}
          tag: ${{ github.ref }}
          repository: ${{ env.ecr_front_repo }}
          dockerfile_dir: ./app/containers/frontend/Dockerfile
  app_back:
    needs: changes
    if: ${{ needs.changes.outputs.app_back == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: push_container
        uses: ./.github/actions/push_container
        with:
          region: ${{ secrets.REGION }}
          iam_role: ${{ secrets.IAM_ROLE }}
          repository: ${{ env.ecr_back_repo }}
          dockerfile_dir: ./app/containers/backend/Dockerfile
